site_name: SinkingYachts
site_url: https://sinking.yachts/

docs_dir: src


markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
    - search
    - awesome-pages:
        filename: .pages.yml


theme:
  name: material

  favicon: assets/img/yacht.jpg
  icon:
    logo: material/sail-boat

  features:
    - navigation.indexes
    
    # how to display sections - bold or collapsible?
    # - navigation.expand
    # - navigation.sections
    
    # tabs at top of page - add later?
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
